/* DB 불러오기용 JS */

const newDB = [
    {
        src:'../images/row2/tap1/01.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185WPSSN] 테일러 반팔 여성페어 크림 (32수)',
        price:76000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/02.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/03.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/04.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/01.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/01.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/01.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row2/tap1/01.png',
        tags:['NEW','커플','COUPON'],
        brand:'ULLALA',
        name:'[25185MPSSN] 테일러 반팔 남성페어 크림 (32수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
]

const styleDB = [
    {
        src:'../images/row3/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row3/tap1/02.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row3/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row3/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
]

const bestDB = [
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/02.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/02.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
    {
        src:'../images/row4/tap1/01.png',
        tags:['NEW','COUPON'],
        brand:'ULLALA',
        name:'[25156WTSSN] 메르 반팔 투피스 크림 (40수)',
        price:78000,
        cart:'../images/small_cart.png',
    },
]

const reviewDB = [
    {
        src:'../images/row5/01.png',
    },
]